// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzlpkbufdwpgdfkbfzmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6bHBrYnVmZHdwZ2Rma2Jmem1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ5NTA2NzAsImV4cCI6MjA4MDUyNjY3MH0.Q4MQwubsst8jXhq4xE5nLpVpNyUnla4Y3FKIJSgfd1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});